export const LOAD_HOT_MOVIES = 'LOAD_HOT_MOVIES';
export const LOAD_HOT_MOVIES_SUCCESS = 'LOAD_HOT_MOVIES_SUCCESS';
export const LOAD_HOT_MOVIES_ERROR = 'LOAD_HOT_MOVIES_ERROR';
export const LOAD_POPULAR_MOVIES = 'LOAD_POPULAR_MOVIES';
export const LOAD_POPULAR_MOVIES_SUCCESS = 'LOAD_POPULAR_MOVIES_SUCCESS';
export const LOAD_POPULAR_MOVIES_ERROR = 'LOAD_POPULAR_MOVIES_ERROR';
